
spring:
  datasource:
    url: jdbc:h2:mem:booking
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        trace: true
  mvc.pathmatch.matching-strategy: ant_path_matcher