/*id, film_id, date_of_booking, seat*/

INSERT INTO booking (ID, FILM_ID, DATE_OF_BOOKING, SEAT) VALUES(30000, 1, CURRENT_TIMESTAMP(), 1);
INSERT INTO booking (ID, FILM_ID, DATE_OF_BOOKING, SEAT) VALUES(30001, 1, CURRENT_TIMESTAMP(), 2);
INSERT INTO booking (ID, FILM_ID, DATE_OF_BOOKING, SEAT) VALUES(30002, 2, CURRENT_TIMESTAMP(), 1);